name: Ruby

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Install sqlite3 package
      run: |
        sudo apt-get install -y libsqlite3-dev
    - name: Set Google Calendar credentials
      run: |
        echo "${{ secrets.GOOGLE_CALENDAR_CREDENTIAL }}" > lib/api/google_calendar/credentials.json
    - name: Build and test with Rake
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        touch app_test.db
        APP_DB_ENV=test bundle exec rake
